In [2]:
import numpy as np
np.set_printoptions(suppress=True)

In [3]:
radius = 10 # km
altitude = 9990 # km
detector_size = 0.1 # mm
focal_length = 50 # mm
lines = 16
exposure_duration = 0.1 # seconds

In [4]:
positions = []
velocities = []
quats = []
for i in np.arange(0,16):
    angle = i*detector_size/(radius+altitude)
    position = (radius+altitude) * np.array([np.cos(angle), 0, -np.sin(angle)])
    positions.append(position)
    velocity = (radius+altitude) * np.array([-np.sin(angle), 0, -np.cos(angle)])
    velocities.append(velocity)
    camera_angle = -np.pi/2 + angle
    quat = np.array([0, np.sin(camera_angle/2), 0, np.cos(camera_angle/2)])
    quats.append(quat)
for pos in positions:
    print(pos)
for vel in velocities:
    print(vel)
for quat in quats:
    print(quat)

[1050.    0.   -0.]
[1049.99999524    0.           -0.1       ]
[1049.99998095    0.           -0.2       ]
[1049.99995714    0.           -0.3       ]
[1049.99992381    0.           -0.39999999]
[1049.99988095    0.           -0.49999998]
[1049.99982857    0.           -0.59999997]
[1049.99976667    0.           -0.69999995]
[1049.99969524    0.           -0.79999992]
[1049.99961429    0.           -0.89999989]
[1049.99952381    0.           -0.99999985]
[1049.99942381    0.           -1.0999998 ]
[1049.99931429    0.           -1.19999974]
[1049.99919524    0.           -1.29999967]
[1049.99906667    0.           -1.39999959]
[1049.99892857    0.           -1.49999949]
[   -0.     0. -1050.]
[   -0.1            0.         -1049.99999524]
[   -0.2            0.         -1049.99998095]
[   -0.3            0.         -1049.99995714]
[   -0.39999999     0.         -1049.99992381]
[   -0.49999998     0.         -1049.99988095]
[   -0.59999997     0.         -1049.99982857]
[   -0.69999995